// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKS3gwCL3AkKY_9-VExq53nmY-0r5TmFA',
    appId: '1:785658408930:web:9aa98f16fe166682e213bb',
    messagingSenderId: '785658408930',
    projectId: 'flutter-login-app-60173',
    authDomain: 'flutter-login-app-60173.firebaseapp.com',
    storageBucket: 'flutter-login-app-60173.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh6BJdvPWmbs7HVOYrdDhPEEB6XSg_OAQ',
    appId: '1:785658408930:android:28f53da70bd15d08e213bb',
    messagingSenderId: '785658408930',
    projectId: 'flutter-login-app-60173',
    storageBucket: 'flutter-login-app-60173.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL_AnR82kLA8jFP0htFJ1m2opPyyPLuiY',
    appId: '1:785658408930:ios:b5e8553c7f866d17e213bb',
    messagingSenderId: '785658408930',
    projectId: 'flutter-login-app-60173',
    storageBucket: 'flutter-login-app-60173.appspot.com',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL_AnR82kLA8jFP0htFJ1m2opPyyPLuiY',
    appId: '1:785658408930:ios:cb1a74a4ce7c536ce213bb',
    messagingSenderId: '785658408930',
    projectId: 'flutter-login-app-60173',
    storageBucket: 'flutter-login-app-60173.appspot.com',
    iosBundleId: 'com.example.loginApp.RunnerTests',
  );
}
